### ISSUE TITLE
error - Error: Unrecognized chain name or RPC url: rinkeby

### ISSUE THREAD

**Issue by francestu96** [thirdweb-example/thirdweb-auth-next-auth#1]
As the title suggests, when I install all the dependencies and launch the app, it returns this error even if I chose a different chain from **Rinkeby** in **_app.tsx**.

How can i solve this?

**Comment by jarrodwatts** [comment]
can you share the code change you have made and the error message?

**Comment by jon577** [comment]
@jarrodwatts I am also receiving this error, could you kindly help identify the issue? I have attempted reinstalling thirdweb to no avail.

Server Error
Error: Unrecognized chain name or RPC url: rinkeby

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.getProviderForNetwork
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/@thirdweb-dev/sdk/dist/thirdweb-dev-sdk.cjs.dev.js (1195:15)
<unknown>
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.cjs.dev.js (745:49)
Array.reduce
<anonymous>
<unknown>
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.cjs.dev.js (744:30)
Object.useMemo
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/react-dom/cjs/react-dom-server.browser.development.js (4984:19)
Object.useMemo
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/react/cjs/react.development.js (1648:21)
ThirdwebProvider
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/@thirdweb-dev/react/dist/thirdweb-dev-react.cjs.dev.js (743:28)
renderWithHooks
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5471:16)
renderIndeterminateComponent
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5544:15)
renderElement
file:///Users/jon/Desktop/Lottery/lottery-yt-dapp/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5759:7)
```

The app.tsx file is as follows:

**import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ChainId, ThirdwebProvider } from "@thirdweb-dev/react";
import { Toaster } from 'react-hot-toast';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThirdwebProvider desiredChainId={ChainId.Mumbai}>
      <Component {...pageProps} />
      <Toaster />
    </ThirdwebProvider>
  )
}

export default MyApp**

**Comment by jarrodwatts** [comment]
Hey @jon577 - Rinkeby is now deprecated - you can use `"goerli"` instead of rinkeby

e.g. `ChainId.Goerli`

**Comment by jon577** [comment]
Pardon, but I'm attempting to use ChainId.Mumbai. I don't understand why Rinkeby is even being queried at all, as it's not referenced in my app.

**Comment by jon577** [comment]
@jarrodwatts Do I need to create a new issue given this one was marked completed?
